Allow max number of retries for ac-retry.

diff --git a/bin/ac-retry b/bin/ac-retry
--- a/bin/ac-retry
+++ b/bin/ac-retry
@@ -2,8 +2,32 @@
 
 source ac-bash-preamble || exit 1
 
-while ! "$@" ; do
-	echo "Error running command '$@'"
-	echo "Retrying in 10 seconds ..."
-	sleep 10
+max_attempts=2
+cooldown=10
+
+while getopts ":n:" opt; do
+    case "$opt" in
+        n)
+            max_attempts="$OPTARG"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+    esac
 done
+
+shift $((OPTIND-1))
+
+if [[ "$max_attempts" == 0 ]] ; then
+    while ! "$@" ; do
+        sleep "$cooldown"
+    done
+    exit 0
+else
+    for ((i=0;i!="$max_attempts";i++)) ; do
+        if "$@" ; then exit 0 ; fi
+        sleep "$cooldown"
+    done
+    exit 1
+fi
